Repository RooftopGreenLight/urbanIsland-front-end, pull requests merged in 2022-08, with the labels that each got.

#7 #1 - 메인 페이지 디자인 레이아웃 적용
  .env
  package-lock.json
  package.json
  src/api/accountControl.js
  src/api/axiosInstance.js
  src/assets/css/modal.css
  src/assets/img/background1.jpg
  src/assets/img/background2.jpg
  src/assets/img/background3.jpg
  src/assets/img/background4.jpg
  src/components/common/Header.jsx
  src/components/common/Navbar.jsx
  src/components/main/Home/Home.jsx
  src/components/main/Login/Login.jsx
  src/components/main/Login/LoginForm.jsx
  src/components/main/Login/LoginSocial.jsx
  src/components/main/Login/RegisterSection.jsx
  src/components/main/Signup/Modal.js
  src/components/main/Signup/Signup.jsx
  src/components/template/BaseTemplate.jsx
  src/constants/MainPageBtn.js
  src/fonts/font.css
  src/pages/MainPage.jsx
  src/styles/Animation.js
Labels: enhancement, development

#11 메인 페이지 리디자인 작업
  src/api/accountControl.js
  src/assets/img/background2.jpg
  src/assets/img/background3.jpg
  src/assets/img/background4.jpg
  src/components/common/Footer.jsx
  src/components/common/Header.jsx
  src/components/common/Navbar.jsx
  src/components/main/Home/Home.jsx
  src/components/main/Home/HomeBottomText.jsx
  src/components/main/Home/HomeBtnList.jsx
  src/components/main/Home/Information/InfoContent.jsx
  src/components/main/Home/Information/Information.jsx
  src/components/main/Login/RegisterSection.jsx
  src/components/template/BaseTemplate.jsx
  src/constants/MainPageBtn.js
  src/constants/MainPageInformation.js
  src/styles/Animation.js
Labels: enhancement

#17 Feature : OAuth2, 채팅방 모듈 기능
  .env
  package-lock.json
  package.json
  public/index.html
  src/api/accountControl.js
  src/api/axiosInstance.js
  src/api/chattingControl.js
  src/api/oAuth.js
  src/assets/icon/kakaotalk.svg
  src/assets/icon/naver.svg
  src/components/common/Modal/ModalPortal.jsx
  src/components/main/Auth/SocialAuthConfirm.jsx
  src/components/main/Chat/ChatModal.jsx
  src/components/main/Chat/ChatRoom.jsx
  src/components/main/Chat/ChatRoomPage.jsx
  src/components/main/Home/HomeBtnList.jsx
  src/components/main/Login/LoginSocial.jsx
  src/components/main/Signup/SignupForm.jsx
  src/components/main/Signup/SignupModal.jsx
  src/hook/useModal.js
  src/index.js
  src/module/Auth.js
  src/module/Modal.js
  src/pages/MainPage.jsx
Labels: enhancement, development

#18 Feat : OAuth2, WebSocket 채팅 모듈 기능 추가
  .env
  package-lock.json
  package.json
  public/index.html
  src/api/accountControl.js
  src/api/axiosInstance.js
  src/api/chattingControl.js
  src/api/oAuth.js
  src/assets/icon/kakaotalk.svg
  src/assets/icon/naver.svg
  src/components/common/Modal/ModalPortal.jsx
  src/components/main/Auth/SocialAuthConfirm.jsx
  src/components/main/Chat/ChatModal.jsx
  src/components/main/Chat/ChatRoom.jsx
  src/components/main/Chat/ChatRoomPage.jsx
  src/components/main/Home/HomeBtnList.jsx
  src/components/main/Login/LoginSocial.jsx
  src/components/main/Signup/SignupForm.jsx
  src/components/main/Signup/SignupModal.jsx
  src/hook/useModal.js
  src/index.js
  src/module/Auth.js
  src/module/Modal.js
  src/pages/MainPage.jsx
Labels: enhancement, development

#16 Feature/mypage
  src/api/mypageControl.js
  src/components/main/Mypage/MypageBox.jsx
  src/components/main/Mypage/Profile.jsx
  src/components/main/Mypage/Rooftop.jsx
  src/pages/MainPage.jsx
Labels: enhancement, development

#20 #Fix : Swagger API 명세에 맞게 Register Form 수정
  src/api/accountControl.js
  src/components/main/Signup/SignupForm.jsx
Labels: bug, enhancement

#21 # Feat : Chat Modal 레이아웃 디자인 및 기능 구현 완료
  src/api/chattingControl.js
  src/components/main/Chat/ChatMessage.jsx
  src/components/main/Chat/ChatModal.jsx
  src/components/main/Chat/ChatRoom.jsx
  src/components/main/Chat/ChatRoomInfo.jsx
  src/components/main/Chat/ChatRoomPage.jsx
  src/components/main/Chat/NoticeEmpty/NoticeEmptyChatMessage.jsx
  src/components/main/Chat/NoticeEmpty/NoticeEmptyChatRoom.jsx
  src/components/main/Home/HomeBtnList.jsx
  src/pages/MainPage.jsx
Labels: enhancement, development

#24 # Feat : 옥상 시설 등록, 옥상 녹화 신청 페이지 추가
  .env
  src/api/accountControl.js
  src/api/axiosInstance.js
  src/api/oAuth.js
  src/api/roofTopControl.js
  src/components/common/Modal/ModalPortal.jsx
  src/components/common/SidoGungu.jsx
  src/components/main/Chat/ChatRoomInfo.jsx
  src/components/main/RoofTop/ApplyRoofTop.jsx
  src/components/main/RoofTop/ApplyRoofTop/ApplyAvailableInfo.jsx
  src/components/main/RoofTop/ApplyRoofTop/ApplyBaseInfo.jsx
  src/components/main/RoofTop/ApplyRoofTop/ApplyDetailInfo.jsx
  src/components/main/RoofTop/ApplyRoofTop/ApplyDetailView.jsx
  src/components/main/RoofTop/ApplyRoofTop/ApplyExtraOption.jsx
  src/components/main/RoofTop/ApplyRoofTop/ApplyImgList.jsx
  src/components/main/RoofTop/ApplyRoofTop/Modal/SetAvailablePersonModal.jsx
  src/components/main/RoofTop/ApplyRoofTop/Modal/SetAvailableTimeModal.jsx
  src/components/main/RoofTop/ApplyRoofTop/Modal/SetFacilitiesModal.jsx
  src/components/main/RoofTop/RequestGreenBee/Modal/SetRequiredOption.jsx
  src/components/main/RoofTop/RequestGreenBee/RequestDeadLine.jsx
  src/components/main/RoofTop/RequestGreenBee/RequestImgList.jsx
  src/components/main/RoofTop/RequestToGreenBee.jsx
  src/constants/FeedbackMsg.js
  src/constants/RequiredRoofTopOption.js
  src/constants/RoofTopFacilities.js
  src/constants/SidoGunguList.js
  src/index.js
  src/module/ApplyRoofTop.js
  src/pages/MainPage.jsx
Labels: enhancement, development

#26 # Feat : 옥상 녹화 및 옥상 시설 신규 등록 시스템 제작
  src/api/controls/roofTopControl.js
  src/components/common/SidoGungu.jsx
  src/components/main/Mypage/RooftopOwner/Modal/RooftopModal.jsx
  src/components/main/RoofTop/ApplyRoofTop.jsx
  src/components/main/RoofTop/ApplyRoofTop/ApplyAvailableInfo.jsx
  src/components/main/RoofTop/ApplyRoofTop/ApplyBaseInfo.jsx
  src/components/main/RoofTop/ApplyRoofTop/ApplyDetailInfo.jsx
  src/components/main/RoofTop/ApplyRoofTop/ApplyDetailView.jsx
  src/components/main/RoofTop/ApplyRoofTop/ApplyExtraOption.jsx
  src/components/main/RoofTop/ApplyRoofTop/ApplyImgList.jsx
  src/components/main/RoofTop/ApplyRoofTop/ApplySidoList.jsx
  src/components/main/RoofTop/ApplyRoofTop/Modal/SetAvailablePersonModal.jsx
  src/components/main/RoofTop/ApplyRoofTop/Modal/SetAvailableTimeModal.jsx
  src/components/main/RoofTop/ApplyRoofTop/Modal/SetFacilitiesModal.jsx
  src/components/main/RoofTop/RequestGreenBee/Modal/SetRequiredOption.jsx
  src/components/main/RoofTop/RequestGreenBee/RequestDetailView.jsx
  src/components/main/RoofTop/RequestGreenBee/RequestImgList.jsx
  src/components/main/RoofTop/RequestToGreenBee.jsx
  src/constants/RoofTopFacilities.js
  src/pages/MainPage.jsx
Labels: enhancement, development

#28 Feature/filter
  package-lock.json
  package.json
  src/api/controls/roofTopControl.js
  src/components/main/Reservation/CustomSlider.jsx
  src/components/main/Reservation/FilterCheckBox.jsx
  src/components/main/Reservation/Modals/DetailFilterModal.jsx
  src/components/main/Reservation/Modals/NumFilterModal.jsx
  src/components/main/Reservation/Modals/RegionFilterModal.jsx
  src/components/main/Reservation/Modals/TimeFilterModal.jsx
  src/components/main/Reservation/Reservation.jsx
  src/components/main/Reservation/ReservationCard.jsx
  src/pages/Container/ReservationContainer.jsx
  src/pages/MainPage.jsx
Labels: development

#29 # Feat : 마이페이지 레이아웃 수정 작업
  src/api/axiosInstance.js
  src/api/controls/accountControl.js
  src/api/controls/greenbeeControl.js
  src/api/controls/mypageControl.js
  src/api/controls/ownerControl.js
  src/components/main/Mypage/Greenbee/Greenbee.jsx
  src/components/main/Mypage/Greenbee/Modal/FindMyRooftopOwner.jsx
  src/components/main/Mypage/Greenbee/RequiredGreeningList.jsx
  src/components/main/Mypage/Profile/MakeGreenbeeAccount.jsx
  src/components/main/Mypage/Profile/Modal/ApplyModal.jsx
  src/components/main/Mypage/Profile/Modal/MypageBoxModal.jsx
  src/components/main/Mypage/Profile/MypageBox.jsx
  src/components/main/Mypage/Profile/Profile.jsx
  src/components/main/Mypage/RooftopOwner/Modal/RooftopModal.jsx
  src/components/main/Mypage/RooftopOwner/Modal/WaitingGreenbeeAcceptModal.jsx
  src/components/main/Mypage/RooftopOwner/Modal/WaitingGreenbeeModal.jsx
  src/components/main/Mypage/RooftopOwner/Modal/WaitingRooftopModal.jsx
  src/components/main/Mypage/RooftopOwner/Rooftop.jsx
  src/components/main/Mypage/Schedule/Schedule.jsx
  src/components/main/RoofTop/ApplyRoofTop.jsx
  src/components/template/BaseTemplate.jsx
  src/components/template/MypageTemplate.jsx
  src/pages/Container/LoginContainer.jsx
  src/pages/Container/MypageContainer.jsx
  src/pages/MainPage.jsx
Labels: bug, enhancement, development

#30 # Feat : 옥상 녹화 시설, 그린비 시스템, 로그인 모듈 등 기능 추가 / 수정
  src/api/controls/accountControl.js
  src/api/controls/greenbeeControl.js
  src/api/controls/ownerControl.js
  src/components/common/Navbar.jsx
  src/components/main/Chat/ChatRoomPage.jsx
  src/components/main/Home/HomeBtnList.jsx
  src/components/main/Login/LoginForm.jsx
  src/components/main/Mypage/Greenbee/Greenbee.jsx
  src/components/main/Mypage/Greenbee/Modal/FindMyRooftopOwner.jsx
  src/components/main/Mypage/Greenbee/RequiredGreeningList.jsx
  src/components/main/Mypage/Profile/MakeGreenbeeAccount.jsx
  src/components/main/Mypage/Profile/MypageBox.jsx
  src/components/main/Mypage/RooftopOwner/Modal/WaitingGreenbeeModal.jsx
  src/components/main/Mypage/RooftopOwner/Modal/WaitingRooftopModal.jsx
  src/components/main/Mypage/Schedule/Schedule.jsx
  src/constants/WaitingRooftopStatus.js
  src/index.js
  src/module/ApplyRoofTop.js
  src/module/Auth.js
  src/pages/Container/MypageContainer.jsx
  src/pages/MainPage.jsx
Labels: enhancement, development

#33 # Fix : 마이페이지 어드민, 옥상지기 관련 시스템 일부 기능 수정
  src/api/axiosInstance.js
  src/api/controls/accountControl.js
  src/api/controls/adminControl.js
  src/components/common/Modal/ModalPortal.jsx
  src/components/main/Mypage/Admin/Admin.jsx
  src/components/main/Mypage/RooftopOwner/Modal/WaitingGreenbeeAcceptModal.jsx
  src/components/main/Mypage/RooftopOwner/Modal/WaitingGreenbeeModal.jsx
  src/components/main/Mypage/RooftopOwner/Modal/WaitingRooftopModal.jsx
  src/components/main/RoofTop/ApplyRoofTop.jsx
  src/components/main/RoofTop/ApplyRoofTop/ApplyAvailableInfo.jsx
  src/components/main/RoofTop/ApplyRoofTop/ApplySidoList.jsx
  src/components/main/RoofTop/ApplyRoofTop/Modal/SetFacilitiesModal.jsx
  src/components/main/RoofTop/RequestGreenBee/Modal/SetRequiredOptionModal.jsx
  src/components/main/RoofTop/RequestToGreenBee.jsx
  src/components/main/Signup/SignupForm.jsx
  src/constants/RequiredRoofTopOption.js
  src/constants/RoofTopFacilities.js
Labels: bug, enhancement

#35 # Feat : 기능 별 라우트 세분화, 예약 페이지 레이아웃 추가
  src/api/controls/accountControl.js
  src/api/controls/greenbeeControl.js
  src/api/controls/roofTopControl.js
  src/components/common/Navbar.jsx
  src/components/main/Home/HomeBtnList.jsx
  src/components/main/Mypage/Admin/Admin.jsx
  src/components/main/Mypage/Greenbee/Greenbee.jsx
  src/components/main/Mypage/Greenbee/GreenbeeInfo.jsx
  src/components/main/Mypage/Greenbee/RequiredGreeningList.jsx
  src/components/main/Mypage/Greenbee/RequiredGreeningRooftop.jsx
  src/components/main/Mypage/Profile/Profile.jsx
  src/components/main/Mypage/RooftopOwner/Modal/WaitingGreenbeeModal.jsx
  src/components/main/Mypage/RooftopOwner/OwnRooftop.jsx
  src/components/main/Mypage/RooftopOwner/Rooftop.jsx
  src/components/main/Reservation/Reservation.jsx
  src/components/main/RoofTop/ApplyRoofTop/ApplyDetailView.jsx
  src/components/main/RoofTop/ApplyRoofTop/ApplyExtraOption.jsx
  src/components/main/RoofTop/RequestGreenBee/Modal/SetRequiredOptionModal.jsx
  src/components/main/RoofTop/RequestGreenBee/RequestDeadLine.jsx
  src/components/main/RoofTop/RequestGreenBee/RequestDetailView.jsx
  src/components/main/RoofTop/RequestGreenBee/RequestImgList.jsx
  src/components/main/RoofTop/RequestToGreenBee.jsx
  src/components/main/Signup/SignupModal.jsx
  src/constants/RequestDeadLineDate.js
  src/pages/Container/MypageContainer.jsx
  src/pages/Container/ReservationContainer.jsx
  src/pages/MainPage.jsx
Labels: bug, enhancement, development
